version: '2'
services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./src_app:/var/www/html/src_app
            - ./site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network

    php:
        image: spalacios/php_73_fpm:v.1.0.0
        # container_name: phpfpm
        volumes:
            - ./src_app:/var/www/html/src_app
        networks:
            - code-network

    mysql:
        image: mysql:5.7
        #restart: always
        # container_name: mysql
        environment:
            MYSQL_DATABASE: 'db'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'user'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'password'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'password'
        ports:
            # <Port exposed> : < MySQL Port running inside container>
            - "3306:3306"
        expose:
            # Opens port 3306 on the container
            - "3306"
        networks:
            - code-network
        # Where our data will be persisted
        volumes:
            - ./db-mysql:/var/lib/mysql
            - ./dumps:/dumps

networks:
    code-network:
        driver: bridge
